/* Auto-generated by tools/extract_hud_layout.py from the
 * accepted Level-1 ground-truth frame 8881. DO NOT EDIT.
 * Screen-space quads in a 640x480 reference space (normalized,
 * top-left origin). dynamic=1 marks counter digit cells that
 * hud.c replaces with the live GameState number. */
#ifndef HUD_LAYOUT_GENERATED_H
#define HUD_LAYOUT_GENERATED_H

typedef struct {
    const char *texture;   /* engine asset path */
    const char *role;      /* widget role (see extractor) */
    float nx, ny, nw, nh;  /* normalized 640x480 rect, top-left */
    int   draw_index;      /* source capture draw */
    int   dynamic;         /* 1 = live digit cell (skip static) */
} HudLayoutElem;

typedef struct {
    float nx, ny;          /* leftmost digit-slot top-left */
    float cell_nw, cell_nh;/* digit cell size (normalized) */
    int   slots;           /* number of digit slots (field width) */
} HudCounter;

static const HudLayoutElem HUD_LAYOUT[] = {
    { "assets/hud/capture/tex_03dcdc50_64x64.png", "atom", 0.04922f, 0.00104f, 0.10000f, 0.13333f, 3487, 0 },
    { "assets/hud/capture/tex_03dcd980_16x64.png", "atom", 0.14922f, 0.00104f, 0.02500f, 0.13333f, 3488, 0 },
    { "assets/hud/capture/tex_03dcdb20_64x8.png", "atom", 0.04922f, 0.13437f, 0.10000f, 0.01250f, 3489, 0 },
    { "assets/hud/capture/tex_053aafb8_16x8.png", "atom", 0.14922f, 0.13437f, 0.02500f, 0.01250f, 3490, 0 },
    { "assets/hud/capture/tex_03dcd7e0_16x64.png", "status_icon", 0.00859f, 0.20052f, 0.02250f, 0.02212f, 3491, 0 },
    { "assets/hud/capture/tex_0540af58_128x256.png", "status_icon", 0.03109f, 0.20052f, 0.01969f, 0.02212f, 3492, 0 },
    { "assets/hud/capture/tex_03dcde60_256x32.png", "status_icon", 0.00859f, 0.22264f, 0.02250f, 0.01590f, 3493, 0 },
    { "assets/hud/capture/tex_053aafd8_128x256.png", "status_icon", 0.03109f, 0.22264f, 0.01969f, 0.01590f, 3494, 0 },
    { "assets/hud/capture/tex_0444dfe0_16x64.png", "gauge_frame", 0.00391f, 0.01562f, 0.02500f, 0.13333f, 3495, 0 },
    { "assets/hud/capture/tex_05e102d0_16x64.png", "gauge_frame", 0.02891f, 0.01562f, 0.02188f, 0.13333f, 3496, 0 },
    { "assets/hud/capture/tex_05479fe8_16x64.png", "gauge_frame", 0.00391f, 0.14896f, 0.02500f, 0.09583f, 3497, 0 },
    { "assets/hud/capture/tex_03da0ff0_16x64.png", "gauge_frame", 0.02891f, 0.14896f, 0.02188f, 0.09583f, 3498, 0 },
    { "assets/hud/capture/tex_053125b8_64x64.png", "gadget", -0.00078f, 0.85521f, 0.10000f, 0.13333f, 3499, 0 },
    { "assets/hud/capture/tex_051d8e90_16x64.png", "gadget", 0.09922f, 0.85521f, 0.02500f, 0.13333f, 3500, 0 },
    { "assets/hud/capture/tex_051d9f98_64x8.png", "gadget", -0.00078f, 0.98854f, 0.10000f, 0.01250f, 3501, 0 },
    { "assets/hud/capture/tex_0547fdc0_16x8.png", "gadget", 0.09922f, 0.98854f, 0.02500f, 0.01250f, 3502, 0 },
    { "assets/hud/capture/tex_0020dfa0_32x32.png", "counter_items", 0.06172f, 0.14062f, 0.05000f, 0.06667f, 3507, 1 },
    { "assets/hud/capture/tex_05d49488_32x32.png", "counter_items", 0.11172f, 0.14062f, 0.05000f, 0.06667f, 3508, 1 },
    { "assets/hud/capture/tex_00161b18_16x16.png", "counter_score", 0.81953f, 0.93854f, 0.02500f, 0.03333f, 3509, 1 },
    { "assets/hud/capture/tex_00161b18_16x16.png", "counter_score", 0.84453f, 0.93854f, 0.02500f, 0.03333f, 3510, 1 },
    { "assets/hud/capture/tex_00161b18_16x16.png", "counter_score", 0.86953f, 0.93854f, 0.02500f, 0.03333f, 3511, 1 },
    { "assets/hud/capture/tex_00161c30_16x16.png", "counter_score", 0.89453f, 0.93854f, 0.02500f, 0.03333f, 3512, 1 },
    { "assets/hud/capture/tex_002309b8_4x16.png", "counter_score", 0.91953f, 0.93854f, 0.00625f, 0.03333f, 3513, 0 },
    { "assets/hud/capture/tex_00230cc0_16x4.png", "counter_score", 0.89453f, 0.97188f, 0.02500f, 0.00833f, 3514, 0 },
    { "assets/hud/capture/tex_00230d30_4x4.png", "counter_score", 0.91953f, 0.97188f, 0.00625f, 0.00833f, 3515, 0 },
    { "assets/hud/capture/tex_00230c10_16x16.png", "counter_score", 0.92578f, 0.93854f, 0.02500f, 0.03333f, 3516, 1 },
    { "assets/hud/capture/tex_052aac58_4x16.png", "counter_score", 0.95078f, 0.93854f, 0.00625f, 0.03333f, 3517, 0 },
    { "assets/hud/capture/tex_052ea228_16x4.png", "counter_score", 0.92578f, 0.97188f, 0.02500f, 0.00833f, 3518, 0 },
    { "assets/hud/capture/tex_052e9d08_4x4.png", "counter_score", 0.95078f, 0.97188f, 0.00625f, 0.00833f, 3519, 0 },
    { "assets/hud/capture/tex_052ea198_16x16.png", "counter_score", 0.95703f, 0.93854f, 0.02500f, 0.03333f, 3520, 1 },
    { "assets/hud/capture/tex_052ea208_4x16.png", "counter_score", 0.98203f, 0.93854f, 0.00625f, 0.03333f, 3521, 0 },
    { "assets/hud/capture/tex_05d496f8_16x4.png", "counter_score", 0.95703f, 0.97188f, 0.02500f, 0.00833f, 3522, 0 },
    { "assets/hud/capture/tex_05d497f0_4x4.png", "counter_score", 0.98203f, 0.97188f, 0.00625f, 0.00833f, 3523, 0 },
};
static const int HUD_LAYOUT_COUNT = 33;

static const HudCounter HUD_COUNTER_ITEMS = { 0.06172f, 0.14062f, 0.05000f, 0.06667f, 2 };
static const HudCounter HUD_COUNTER_SCORE = { 0.81953f, 0.93854f, 0.02500f, 0.03333f, 6 };

#define HUD_DIGIT_PATH "assets/hud/capture/font/big_%d.png"

#endif /* HUD_LAYOUT_GENERATED_H */
