/* GENERATED by tools/gen_picture_pregrants.py from the .gam corpus.
   Do not edit by hand -- re-run the generator.

   Pictures a cold entry into a level pre-grants, because the level gates on
   them but never awards them. Counts are that level's whole demand: the gate
   consumes (CheckRequiredPicAndConsume, 00436830), so one copy would open one
   gate. See docs/picture_flag_wiring_plan.md. */
#ifndef PICTURE_PREGRANTS_GENERATED_H
#define PICTURE_PREGRANTS_GENERATED_H

#include <stddef.h>

typedef struct {
    const char *level;  /* lowercased .gam stem */
    int         id;     /* PIC_NUMBER */
    int         count;  /* copies to grant */
} PicturePreGrant;

static const PicturePreGrant PICTURE_PREGRANTS[] = {
    { "level1a", 10, 4 },
    { "level1b", 12, 4 },
    { "level1b", 14, 1 },
    { "level1c", 23, 18 },
    { "level4a", 8, 12 },
};

#define PICTURE_PREGRANT_COUNT \
    (sizeof(PICTURE_PREGRANTS) / sizeof(PICTURE_PREGRANTS[0]))

#endif
