/* GENERATED by instrument/diff/gen_canon_header.py from build/canon.json.
 * Do not edit by hand -- re-run the generator. Phase 12 canon values. */
#ifndef CANON_DATA_H
#define CANON_DATA_H

/* frame 16565  source level1_session.omtc  names_resolved=True */

#define CANON_LIGHTING_ENABLED 0
#define CANON_AMBIENT_R 0.200000f
#define CANON_AMBIENT_G 0.200000f
#define CANON_AMBIENT_B 0.200000f
#define CANON_LIGHT_COUNT 0
#define CANON_LIGHT_DIR_X 0.577000f
#define CANON_LIGHT_DIR_Y 0.577000f
#define CANON_LIGHT_DIR_Z 0.577000f
#define CANON_LIGHT_DIFF_R 1.000000f
#define CANON_LIGHT_DIFF_G 1.000000f
#define CANON_LIGHT_DIFF_B 1.000000f

#define CANON_GROUND_TEXTURE "assets/png/mud.png"  /* canon ground asset null/synthetic -> fallback */
#define CANON_GROUND_Y_SPAN 68118.319000f      /* raw, outlier-inflated */
#define CANON_GROUND_Y_SPAN_ROBUST 24208.660000f  /* 1.5*IQR core span */
#define CANON_GROUND_TILE_YEXT 5786.111000f        /* median tile y-extent */
#define CANON_GROUND_FOOTPRINT_X 33143.210000f
#define CANON_GROUND_FOOTPRINT_Z 25003.090000f

#define CANON_WATER_PRESENT 0
#define CANON_WATER_TEXTURE "assets/png/waterlevel4.png"
#define CANON_WATER_CX 0.000000f
#define CANON_WATER_CY 0.000000f
#define CANON_WATER_CZ 0.000000f
#define CANON_WATER_FX 0.000000f
#define CANON_WATER_FZ 0.000000f

#endif /* CANON_DATA_H */
