/* GENERATED by tools/sample_phase1_sky_tint.py.
 * Re-run that tool when build/frame_v4_hudfix_candidate_8881.png or
 * build/native_level1_keyframe_8881.png change.
 * Phase 1 of docs/native_vs_capture_8881_plan.md. */
#ifndef PHASE1_SKY_TINT_H
#define PHASE1_SKY_TINT_H

#define PHASE1_SKY_TOP_R 0.329171f
#define PHASE1_SKY_TOP_G 0.510662f
#define PHASE1_SKY_TOP_B 0.372994f
#define PHASE1_SKY_BOT_R 0.321806f
#define PHASE1_SKY_BOT_G 0.424567f
#define PHASE1_SKY_BOT_B 0.302657f
#define PHASE1_SCENE_TINT_R 0.387796f
#define PHASE1_SCENE_TINT_G 0.480514f
#define PHASE1_SCENE_TINT_B 0.251472f

#endif /* PHASE1_SKY_TINT_H */
