/* GENERATED by tools/sample_phase4_capture_state.py. */
/* Phase 4 measured alpha / blend / fog constants for native Level 1. */
#ifndef PHASE4_CAPTURE_STATE_H
#define PHASE4_CAPTURE_STATE_H

/* Shader-side alpha cutout threshold (capture-derived billboards have
 * real alpha channels from D3D color-keying decoded by the proxy). */
#define PHASE4_ALPHA_CUTOUT_ENABLED 1
#define PHASE4_ALPHA_CUTOUT_THRESHOLD 0.5000f

/* Fog -- not enabled in the captured Level 1 stream; placeholder for
 * a future capture frame that does use it. */
#define PHASE4_FOG_ENABLED 0
#define PHASE4_FOG_COLOR_R 0.0f
#define PHASE4_FOG_COLOR_G 0.0f
#define PHASE4_FOG_COLOR_B 0.0f

#endif /* PHASE4_CAPTURE_STATE_H */
