#!/usr/bin/env python3
r"""
gen_canon_header.py -- turn build/canon.json into src/engine/canon_data.h.

The engine consumes ONLY measured numbers, never magic constants: this script
is the bridge. Re-run it whenever canon.json changes; the header is generated,
not hand-edited. If canon.json is missing, a neutral header is written so the
engine still builds (lighting flat, no water) -- but the canonical path needs
canon.json present.

Texture-name caveat (M5): the original capture's texture SHA-1s rarely match a
decoded PNG, so canon's ground/water *asset names* are usually null. When null,
we fall back to a sensible bound asset (mud.png ground) and mark water absent;
the chosen fallback is recorded in a comment so it is auditable.
"""
import os
import json
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.join(HERE, "..", "..")
CANON = os.path.join(REPO, "build", "canon.json")
OUT = os.path.join(REPO, "src", "engine", "canon_data.h")

GROUND_FALLBACK = "assets/png/mud.png"   # bound when canon can't name the ground


def asset_path(name, fallback):
    """Map a canon asset basename to an engine asset path. canon names that are
    synthetic (tex_xxxx) or null don't resolve -> fallback."""
    if not name or name.startswith("tex_"):
        return fallback, True       # used_fallback = True
    if name.startswith("assets/"):
        return name, False
    return f"assets/png/{name}", False


def main():
    if os.path.exists(CANON):
        with open(CANON) as f:
            c = json.load(f)
    else:
        print(f"[gen_canon] {CANON} missing -- writing neutral header",
              file=sys.stderr)
        c = {}

    lighting_enabled = c.get("lighting_enabled")
    amb = c.get("ambient_rgb") or [0.2, 0.2, 0.2]
    lights = c.get("lights") or []
    ground_y_span = float(c.get("ground_y_span") or 0.0)
    fp = c.get("ground_footprint") or [0.0, 0.0]

    # Robust topography amplitude: the span of ground-tile *center* heights with
    # statistical outliers (1.5*IQR) removed. The raw ground_y_span is inflated
    # by a few elevated pieces (rooftops/mesa) the flat-in-Y classify_ground
    # heuristic counts as ground; the demo carries those as placement meshes,
    # not as ground topography. Median per-tile y_extent is the ground's own
    # local slope budget. Both are measured -- no hand-tuned constants.
    tiles = c.get("ground_tiles") or []
    centers = sorted(d["center"][1] for d in tiles) if tiles else []
    yexts = sorted(d.get("y_extent", 0.0) for d in tiles) if tiles else []

    def _pct(xs, p):
        if not xs:
            return 0.0
        k = (len(xs) - 1) * p
        f = int(k)
        return xs[f] + (xs[min(f + 1, len(xs) - 1)] - xs[f]) * (k - f)

    if centers:
        q1, q3 = _pct(centers, 0.25), _pct(centers, 0.75)
        iqr = q3 - q1
        lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr
        core = [y for y in centers if lo <= y <= hi]
        robust_span = (core[-1] - core[0]) if core else 0.0
    else:
        robust_span = 0.0
    tile_yext = _pct(yexts, 0.5) if yexts else 0.0
    g_name = c.get("ground_texture_asset")
    g_path, g_fallback = asset_path(g_name, GROUND_FALLBACK)
    w_name = c.get("water_texture_asset")
    water_draws = c.get("water_draws") or []

    # First DIR light (direction + diffuse), if any; else a neutral down-ish dir.
    dir_light = next((l for l in lights if l.get("type") == "DIR"), None)
    if dir_light:
        ld = dir_light["direction"][:3]
        # D3D light direction points the way light travels; the shader wants the
        # vector toward the light, so negate.
        ldir = [-ld[0], -ld[1], -ld[2]]
        ldiff = dir_light["diffuse"][:3]
    else:
        ldir = [0.577, 0.577, 0.577]
        ldiff = [1.0, 1.0, 1.0]

    le = 1 if lighting_enabled else 0  # None -> 0 (flat), matches LIGHTING OFF

    water_present = 1 if water_draws else 0
    if water_present:
        wd = water_draws[0]
        wc = wd.get("center", [0, 0, 0])
        wf = wd.get("footprint", [0, 0])
        w_path, _ = asset_path(w_name, "assets/png/waterlevel4.png")
    else:
        wc = [0, 0, 0]
        wf = [0, 0]
        w_path = "assets/png/waterlevel4.png"

    lines = []
    A = lines.append
    A("/* GENERATED by instrument/diff/gen_canon_header.py from build/canon.json.")
    A(" * Do not edit by hand -- re-run the generator. Phase 12 canon values. */")
    A("#ifndef CANON_DATA_H")
    A("#define CANON_DATA_H")
    A("")
    A(f"/* frame {c.get('frame')}  source {c.get('source')}  "
      f"names_resolved={c.get('names_resolved')} */")
    A("")
    A(f"#define CANON_LIGHTING_ENABLED {le}")
    A(f"#define CANON_AMBIENT_R {amb[0]:.6f}f")
    A(f"#define CANON_AMBIENT_G {amb[1]:.6f}f")
    A(f"#define CANON_AMBIENT_B {amb[2]:.6f}f")
    A(f"#define CANON_LIGHT_COUNT {len(lights)}")
    A(f"#define CANON_LIGHT_DIR_X {ldir[0]:.6f}f")
    A(f"#define CANON_LIGHT_DIR_Y {ldir[1]:.6f}f")
    A(f"#define CANON_LIGHT_DIR_Z {ldir[2]:.6f}f")
    A(f"#define CANON_LIGHT_DIFF_R {ldiff[0]:.6f}f")
    A(f"#define CANON_LIGHT_DIFF_G {ldiff[1]:.6f}f")
    A(f"#define CANON_LIGHT_DIFF_B {ldiff[2]:.6f}f")
    A("")
    cmt = f"  /* canon ground asset null/synthetic -> fallback */" if g_fallback else ""
    A(f'#define CANON_GROUND_TEXTURE "{g_path}"{cmt}')
    A(f"#define CANON_GROUND_Y_SPAN {ground_y_span:.6f}f      /* raw, outlier-inflated */")
    A(f"#define CANON_GROUND_Y_SPAN_ROBUST {robust_span:.6f}f  /* 1.5*IQR core span */")
    A(f"#define CANON_GROUND_TILE_YEXT {tile_yext:.6f}f        /* median tile y-extent */")
    A(f"#define CANON_GROUND_FOOTPRINT_X {float(fp[0]):.6f}f")
    A(f"#define CANON_GROUND_FOOTPRINT_Z {float(fp[1]):.6f}f")
    A("")
    A(f"#define CANON_WATER_PRESENT {water_present}")
    A(f'#define CANON_WATER_TEXTURE "{w_path}"')
    A(f"#define CANON_WATER_CX {float(wc[0]):.6f}f")
    A(f"#define CANON_WATER_CY {float(wc[1]):.6f}f")
    A(f"#define CANON_WATER_CZ {float(wc[2]):.6f}f")
    A(f"#define CANON_WATER_FX {float(wf[0]):.6f}f")
    A(f"#define CANON_WATER_FZ {float(wf[1]):.6f}f")
    A("")
    A("#endif /* CANON_DATA_H */")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[gen_canon] wrote {OUT} (lighting_enabled={le}, "
          f"ground={g_path}, water_present={water_present})")


if __name__ == "__main__":
    main()
