#!/usr/bin/env python3
"""
build_level_entity_index.py — per-level entity survey for the decomp campaign.

Cross-references every original-game (`Neutron.exe`) level `.gam` file with the
`CLevel*Game` / `CLevelVR0N` class that loads it, and folds in the one shipped
`.tsk` task file (`NewGame.tsk`) for Level 1's initial entity-state overrides.

Output: `docs/tsk_data/all_entities.json` — the reference the `CLevel*Game`
spec batch is grounded in (object FourCC types, named ObjectTags, spawn, and
per-level mission task). Re-run after editing; idempotent.

Scope: original JNBG only. The "Jimmy vs. Jimmy Negatron" sequel save files
(`JimmyGame*.tsk`) use a different serialization and are out of scope.

Usage: python3 tools/build_level_entity_index.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

from gam_parser import parse_gam          # noqa: E402
from tsk_parser import parse_tsk          # noqa: E402

GAMDIR = ROOT / "assets" / "gam"
TSK_FILE = Path.home() / "xp-jnbg-original" / "NewGame.tsk"
OUT = ROOT / "docs" / "tsk_data" / "all_entities.json"


def class_for_gam(stem: str):
    """Map a `.gam` stem to its CLevel*Game / CLevelVR0N class name."""
    m = re.fullmatch(r"VR(\d+)", stem, re.IGNORECASE)
    if m:
        return f"CLevelVR{int(m.group(1)):02d}"
    m = re.fullmatch(r"level(\d+)([a-z]?)", stem, re.IGNORECASE)
    if m:
        num = m.group(1)             # already no leading zero in filenames
        suffix = m.group(2).upper()
        # CLevel uses zero-padded two-digit level numbers (01..07).
        return f"CLevel{int(num):02d}{suffix}Game"
    return None


def summarize_gam(path: Path) -> dict:
    d = parse_gam(path)
    fourcc_counts: dict = {}
    tags = []
    for obj in d["objects"]:
        t = obj["type"]
        fourcc_counts[t] = fourcc_counts.get(t, 0) + 1
        tag = obj["properties"].get("ObjectTag")
        if tag and tag != "none":
            sx = obj["properties"].get("PositionX")
            tags.append({"type": t, "tag": tag, "pos_x": sx})
    return {
        "object_count": d["object_count"],
        "distinct_fourcc": len(fourcc_counts),
        "fourcc_counts": dict(sorted(fourcc_counts.items())),
        "named_tags": tags,
    }


def main():
    levels = {}
    for gam in sorted(GAMDIR.glob("*.gam"), key=lambda p: p.name.lower()):
        stem = gam.stem
        cls = class_for_gam(stem)
        entry = {
            "class": cls,
            "gam_file": gam.name,
        }
        entry.update(summarize_gam(gam))
        levels[stem.lower()] = entry

    # Fold in the one shipped .tsk: Level 1 (level1b.gam) initial state overrides.
    tsk_overlay = None
    if TSK_FILE.exists():
        t = parse_tsk(str(TSK_FILE))
        si = t.start_info
        tsk_overlay = {
            "source": TSK_FILE.name,
            "gam_file": si.gam_file if si else None,
            "spawn": [si.start_x, si.start_y, si.start_z] if si else None,
            "entities": [{"name": e.name, "state": e.state} for e in t.entities],
        }
        # Attach to whichever level loads that gam.
        if si:
            key = Path(si.gam_file).stem.lower()
            if key in levels:
                levels[key]["tsk_initial_state"] = tsk_overlay["entities"]
                levels[key]["tsk_spawn"] = tsk_overlay["spawn"]

    out = {
        "_about": (
            "Per-level entity survey for the Neutron.exe decomp campaign. Each "
            "key is a level .gam stem; `class` is the CLevel*Game/CLevelVR0N "
            "class that loads it. `tsk_initial_state` (Level 1 only) is the "
            "NewGame.tsk entity-state override table. Generated by "
            "tools/build_level_entity_index.py."
        ),
        "tsk": {"NewGame": tsk_overlay} if tsk_overlay else {},
        "levels": levels,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, indent=2))
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(levels)} levels, "
          f"{sum(1 for v in levels.values() if v['class'])} mapped to classes")
    unmapped = [k for k, v in levels.items() if not v["class"]]
    if unmapped:
        print("  UNMAPPED gam stems (no class):", unmapped)


if __name__ == "__main__":
    main()
