#!/usr/bin/env python3
"""
gen_sprite_chunk_map.py — generate src/game/sprite_chunk_map_generated.h from
assets/parsed/sprites/sprites.json.

The original game's C3DSprite family reads its visual per-instance from the
.gam: SpriteDatabase ("sprites.omt") + SpriteIndex. SpriteIndex is the canvas
*chunk id* inside sprites.omt (verified: 3SM1=37 -> "smoke", 3FUE=40 ->
"plutrod", 3PIC=117 -> "wrench"). The Era-12 extractor records that chunk id
for every exported PNG in sprites.json, so this table is the faithful
chunk-id -> texture-path map for JNBG.

Idempotent; re-run after re-extracting sprites.omt:
    python3 tools/gen_sprite_chunk_map.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Sprite databases the .gam's SpriteDatabase property can name (JNBG).
# C3DSprite family uses sprites.omt; C3DTrigger markers use icons.omt.
DATABASES = ['sprites', 'icons']
DST = os.path.join(ROOT, 'src/game/sprite_chunk_map_generated.h')


def main():
    rows = []
    for db in DATABASES:
        src = os.path.join(ROOT, f'assets/parsed/{db}/{db}.json')
        with open(src) as f:
            data = json.load(f)
        for im in data['images']:
            if im.get('status') != 'ok':
                continue
            path = im['file']
            if not os.path.exists(os.path.join(ROOT, path)):
                raise SystemExit(f'missing sprite image on disk: {path}')
            rows.append((f'{db}.omt', im['chunk_id'], path, im.get('name', '')))

    with open(DST, 'w') as f:
        f.write('/* Generated by tools/gen_sprite_chunk_map.py -- do not edit.\n'
                '   Maps (SpriteDatabase, canvas chunk id) -- the .gam sprite\n'
                '   reference authored by the C3DSprite family -- to the\n'
                '   extracted PNG for that canvas (JNBG game-1). */\n')
        f.write('typedef struct { const char *db; int chunk_id; const char *path; }'
                ' SpriteChunkEntry;\n')
        f.write('static const SpriteChunkEntry SPRITE_CHUNK_MAP[] = {\n')
        for db, cid, path, name in rows:
            f.write(f'    {{ "{db}", {cid:3d}, "{path}" }},  /* {name} */\n')
        f.write('};\n')
        f.write('static const int SPRITE_CHUNK_MAP_N = '
                '(int)(sizeof(SPRITE_CHUNK_MAP) / sizeof(SPRITE_CHUNK_MAP[0]));\n')
    print(f'wrote {DST}: {len(rows)} chunk entries '
          f'({", ".join(d + ".omt" for d in DATABASES)})')


if __name__ == '__main__':
    main()
