#!/usr/bin/env python3
"""gen_picture_pregrants.py -- derive src/game/picture_pregrants_generated.h
from assets/gam/*.gam.

The level browser can drop the player straight into any level. Four levels gate
content on a picture that no row *in that level* awards, so a cold jump into one
of them dead-ends on content that is reachable today:

    level1a needs 10   level1b needs 12 and 14   level1c needs 23   level4a needs 8

The chosen fix (docs/picture_flag_wiring_plan.md, option A) is for a cold entry
to pre-grant exactly those pictures. This tool derives the table instead of
hand-writing it so it cannot drift from the corpus.

Rule, per level:
  supply[id] = rows whose PIC_NUMBER == id
  demand[id] = sum of max(ReqPicNumAmount, 1) over rows whose RequiredPicNum == id
  pre-grant id, demand[id] copies, when demand[id] > 0 and supply[id] == 0

Both halves matter. The *id* set is the set difference (an id the level never
awards); the *count* is the level's whole demand, because the gate consumes --
CheckRequiredPicAndConsume (00436830) subtracts ReqPicNumAmount on success, so
granting one copy of picture 23 would open one of level1c's nine gates.

Read-only and idempotent. Run: python3 tools/gen_picture_pregrants.py
"""

from __future__ import annotations

import collections
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from asset_paths import gam_root  # noqa: E402
from gam_parser import parse_gam  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DST = ROOT / "src/game/picture_pregrants_generated.h"


def scan(gam_dir: Path):
    """-> {level_key: {id: count}} in the shape the generated table needs."""
    supply = collections.defaultdict(collections.Counter)
    demand = collections.defaultdict(collections.Counter)

    for path in sorted(gam_dir.glob("*.gam")):
        level = path.stem.lower()
        for obj in parse_gam(path)["objects"]:
            props = obj["properties"]

            awarded = props.get("PIC_NUMBER", -1)
            if isinstance(awarded, int) and awarded >= 0:
                supply[level][awarded] += 1

            required = props.get("RequiredPicNum", -1)
            if isinstance(required, int) and required >= 0:
                amount = props.get("ReqPicNumAmount", 1)
                if not isinstance(amount, int) or amount < 1:
                    amount = 1
                demand[level][required] += amount

    table = {}
    for level in sorted(demand):
        rows = {pic: n for pic, n in sorted(demand[level].items())
                if supply[level][pic] == 0}
        if rows:
            table[level] = rows
    return table


def render(table) -> str:
    out = [
        "/* GENERATED by tools/gen_picture_pregrants.py from the .gam corpus.",
        "   Do not edit by hand -- re-run the generator.",
        "",
        "   Pictures a cold entry into a level pre-grants, because the level gates on",
        "   them but never awards them. Counts are that level's whole demand: the gate",
        "   consumes (CheckRequiredPicAndConsume, 00436830), so one copy would open one",
        "   gate. See docs/picture_flag_wiring_plan.md. */",
        "#ifndef PICTURE_PREGRANTS_GENERATED_H",
        "#define PICTURE_PREGRANTS_GENERATED_H",
        "",
        "#include <stddef.h>",
        "",
        "typedef struct {",
        "    const char *level;  /* lowercased .gam stem */",
        "    int         id;     /* PIC_NUMBER */",
        "    int         count;  /* copies to grant */",
        "} PicturePreGrant;",
        "",
        "static const PicturePreGrant PICTURE_PREGRANTS[] = {",
    ]
    for level in sorted(table):
        for pic, n in sorted(table[level].items()):
            out.append('    { "%s", %d, %d },' % (level, pic, n))
    out += [
        "};",
        "",
        "#define PICTURE_PREGRANT_COUNT \\",
        "    (sizeof(PICTURE_PREGRANTS) / sizeof(PICTURE_PREGRANTS[0]))",
        "",
        "#endif",
        "",
    ]
    return chr(10).join(out)


def main() -> int:
    gam_dir = gam_root()
    if not gam_dir.is_dir():
        print(f"pregrants SKIP: no gam corpus at {gam_dir}")
        return 0
    table = scan(gam_dir)
    text = render(table)
    if DST.exists() and DST.read_text() == text:
        print(f"pregrants up to date: {DST.relative_to(ROOT)}")
        return 0
    DST.write_text(text)
    rows = sum(len(v) for v in table.values())
    print(f"wrote {DST.relative_to(ROOT)} ({len(table)} levels, {rows} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
